language: python
sudo: false
cache: pip

python:
  - "3.5"

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev
      - python-lxml

env:
  global:
  - VERSION="12.0" LINT_CHECK="1"
  - VERSION="12.0" ODOO_REPO="odoo/odoo" LINT_CHECK="0"

  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"

install:
  - git clone --depth=1 https://github.com/Jarsa/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - if [[ "${OCA_RUNBOT}" == "1" ]]; then git clone --depth=1 git@github.com:odoo/enterprise.git -b $VERSION ${HOME}/enterprise; fi
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
